name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 3 * * 1'

jobs:
  eslint:
    name: Run ESLint Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci  # Clean install, matching the lock file

      - name: Install formatter
        run: npm install --save-dev @microsoft/eslint-formatter-sarif  # Ensure formatter is installed

      - name: Verify dependencies
        run: npm list --depth=0  # Verifies if all dependencies are installed correctly

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npm run lint  # Runs ESLint using your locally defined script
          ls -l  # List files to check if eslint-results.sarif is generated

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
